version: '3.8'
services:
    app:
        build:
            dockerfile: Dockerfile
        depends_on:
            - postgres  
        # volumes:
        #     - ./:/usr/src/app/
        #     - '/usr/src/app/node_modules'
        ports:
            - "3000:3000"
    postgres:
        image: postgres:latest
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=bhumigres
            - POSTGRES_DB=students
        volumes:
            - './database.sql:/docker-entrypoint-initdb.d/database.sql'


# version: '3'

# services:
#   postgres:
#     image: postgres
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: bhumigres
#       POSTGRES_DB: students
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres-data:/var/lib/postgresql/data

#   app:
#     build: .
#     ports:
#       - "3000:3000"
#     depends_on:
#       - postgres

# volumes:
#   postgres-data:









